export type ThemeTokenMap = Record<string, string>;

export type WorldbookTheme = {
  name: string;
  tokens: ThemeTokenMap;
};

const sourceThemes: Record<string, ThemeTokenMap> = {
  'Terminal Amber': {
    '--bg': '#09090b',
    '--text-main': '#e0e0e0',
    '--text-muted': '#737373',
    '--color-sys': '#ff8c00',
    '--color-char': '#d4d4d4',
    '--color-user': '#4caf50',
    '--ide-bg': '#1f1f1f',
    '--ide-editor-bg': '#262626',
    '--ide-border': '#3e3e38',
    '--ide-text': '#c3c1ba',
    '--ide-muted': '#9a988f',
    '--ide-accent': '#d87757',
    '--ide-header-bg': '#1b1b1b',
  },
  'Old BBS FUI': {
    '--bg': '#0a0a0c',
    '--text-main': '#d0d0d0',
    '--text-muted': '#666666',
    '--color-sys': '#00e5ff',
    '--color-char': '#ffb000',
    '--color-user': '#39ff14',
    '--ide-bg': '#0a0a0c',
    '--ide-editor-bg': '#111116',
    '--ide-border': '#333333',
    '--ide-text': '#d0d0d0',
    '--ide-muted': '#666666',
    '--ide-accent': '#00e5ff',
    '--ide-header-bg': '#050505',
  },
  'Codex Archive': {
    '--bg': '#121212',
    '--text-main': '#e4e6eb',
    '--text-muted': '#8b919b',
    '--color-sys': '#d97757',
    '--color-char': '#8b919b',
    '--color-user': '#738b76',
    '--ide-bg': '#191919',
    '--ide-editor-bg': '#1e1e1e',
    '--ide-border': '#303030',
    '--ide-text': '#e4e6eb',
    '--ide-muted': '#8b919b',
    '--ide-accent': '#d97757',
    '--ide-header-bg': '#151515',
  },
  'Monochrome Invert': {
    '--bg': '#050505',
    '--text-main': '#ffffff',
    '--text-muted': '#888888',
    '--color-sys': '#ffffff',
    '--color-char': '#cccccc',
    '--color-user': '#999999',
    '--ide-bg': '#0a0a0a',
    '--ide-editor-bg': '#111111',
    '--ide-border': '#333333',
    '--ide-text': '#ffffff',
    '--ide-muted': '#888888',
    '--ide-accent': '#ffffff',
    '--ide-header-bg': '#000000',
    '--disk-bg': '#111111',
    '--disk-border-color': '#333333',
    '--disk-bg-hover': '#ffffff',
    '--disk-border-hover': '#ffffff',
    '--disk-bg-active': '#cccccc',
    '--disk-border-active': '#cccccc',
    '--disk-text-hover-override': '#000000',
    '--disk-text-active-override': '#000000',
    '--port-bg': '#333333',
    '--port-bg-hover': '#000000',
    '--port-bg-active': '#000000',
  },
  'Akiba Maid War': {
    '--bg': '#0a0508',
    '--text-main': '#fce4ee',
    '--text-muted': '#a37086',
    '--color-sys': '#ff2a85',
    '--color-char': '#ff85b3',
    '--color-user': '#5ce6e6',
    '--ide-bg': '#12080e',
    '--ide-editor-bg': '#180a13',
    '--ide-border': '#3d1829',
    '--ide-text': '#fce4ee',
    '--ide-muted': '#a37086',
    '--ide-accent': '#ff2a85',
    '--ide-header-bg': '#0a0508',
    '--disk-bg': '#170811',
    '--disk-border-color': '#3d1829',
    '--disk-bg-hover': '#ff2a85',
    '--disk-border-hover': '#ff2a85',
    '--disk-bg-active': '#fce4ee',
    '--disk-border-active': '#fce4ee',
    '--disk-text-hover-override': '#14050d',
    '--disk-text-active-override': '#ff2a85',
    '--port-bg': '#3d1829',
    '--port-bg-hover': '#14050d',
    '--port-bg-active': '#ff2a85',
  },
  'ICE Layer': {
    '--bg': '#050a0f',
    '--text-main': '#e0f8ff',
    '--text-muted': '#5a8c9e',
    '--color-sys': '#00f0ff',
    '--color-char': '#00a8ff',
    '--color-user': '#bd00ff',
    '--ide-bg': '#081018',
    '--ide-editor-bg': '#0b1622',
    '--ide-border': '#13313d',
    '--ide-text': '#e0f8ff',
    '--ide-muted': '#5a8c9e',
    '--ide-accent': '#00f0ff',
    '--ide-header-bg': '#050a0f',
    '--disk-bg': '#10252a',
    '--disk-border-color': '#13313d',
    '--disk-bg-hover': '#173b42',
    '--disk-border-hover': '#00f0ff',
    '--disk-bg-active': '#000000',
    '--disk-border-active': '#00f0ff',
    '--port-bg': '#13313d',
    '--port-bg-hover': '#00f0ff',
    '--port-bg-active': '#00f0ff',
  },
  'NERV Terminal': {
    '--bg': '#000000',
    '--text-main': '#39ff14',
    '--text-muted': '#1e8010',
    '--color-sys': '#ff3b00',
    '--color-char': '#39ff14',
    '--color-user': '#ffcc00',
    '--ide-bg': '#050a05',
    '--ide-editor-bg': '#081208',
    '--ide-border': '#1a331a',
    '--ide-text': '#39ff14',
    '--ide-muted': '#1e8010',
    '--ide-accent': '#ff3b00',
    '--ide-header-bg': '#000000',
    '--disk-bg': '#0a1a0a',
    '--disk-border-color': '#1a331a',
    '--disk-bg-hover': '#143314',
    '--disk-border-hover': '#39ff14',
    '--disk-bg-active': '#000000',
    '--disk-border-active': '#ff3b00',
    '--port-bg': '#1a331a',
    '--port-bg-hover': '#39ff14',
    '--port-bg-active': '#ff3b00',
  },
  'Arasaka Corp': {
    '--bg': '#0c0c0c',
    '--text-main': '#ffffff',
    '--text-muted': '#666666',
    '--color-sys': '#d40000',
    '--color-char': '#ffffff',
    '--color-user': '#a00000',
    '--ide-bg': '#121212',
    '--ide-editor-bg': '#181818',
    '--ide-border': '#333333',
    '--ide-text': '#ffffff',
    '--ide-muted': '#666666',
    '--ide-accent': '#d40000',
    '--ide-header-bg': '#0c0c0c',
    '--disk-bg': '#1c1c1c',
    '--disk-border-color': '#333333',
    '--disk-bg-hover': '#2a2a2a',
    '--disk-border-hover': '#ffffff',
    '--disk-bg-active': '#000000',
    '--disk-border-active': '#d40000',
    '--port-bg': '#333333',
    '--port-bg-hover': '#ffffff',
    '--port-bg-active': '#d40000',
  },
  'Null Violet': {
    '--bg': '#07070d',
    '--text-main': '#d8d0e0',
    '--text-muted': '#5a5470',
    '--color-sys': '#8b5cf6',
    '--color-char': '#a8a0b8',
    '--color-user': '#6d28d9',
    '--ide-bg': '#0d0d18',
    '--ide-editor-bg': '#111120',
    '--ide-border': '#2a2640',
    '--ide-text': '#d8d0e0',
    '--ide-muted': '#5a5470',
    '--ide-accent': '#8b5cf6',
    '--ide-header-bg': '#07071a',
    '--disk-bg': '#0f0d1a',
    '--disk-border-color': '#2a2640',
    '--disk-bg-hover': '#1a1530',
    '--disk-border-hover': '#8b5cf6',
    '--disk-bg-active': '#000000',
    '--disk-border-active': '#8b5cf6',
    '--port-bg': '#2a2640',
    '--port-bg-hover': '#8b5cf6',
    '--port-bg-active': '#8b5cf6',
  },
  'Signal Midnight': {
    '--bg': '#040810',
    '--text-main': '#c0d8e8',
    '--text-muted': '#3a5a78',
    '--color-sys': '#2196f3',
    '--color-char': '#7094b0',
    '--color-user': '#1565c0',
    '--ide-bg': '#081020',
    '--ide-editor-bg': '#0c1628',
    '--ide-border': '#1a3050',
    '--ide-text': '#c0d8e8',
    '--ide-muted': '#3a5a78',
    '--ide-accent': '#2196f3',
    '--ide-header-bg': '#040810',
    '--disk-bg': '#0a1820',
    '--disk-border-color': '#1a3050',
    '--disk-bg-hover': '#122840',
    '--disk-border-hover': '#2196f3',
    '--disk-bg-active': '#000408',
    '--disk-border-active': '#2196f3',
    '--port-bg': '#1a3050',
    '--port-bg-hover': '#2196f3',
    '--port-bg-active': '#2196f3',
  },
  'Gilded Wire': {
    '--bg': '#080804',
    '--text-main': '#e8e0c8',
    '--text-muted': '#6a6040',
    '--color-sys': '#d4a520',
    '--color-char': '#b0a070',
    '--color-user': '#a08520',
    '--ide-bg': '#10100a',
    '--ide-editor-bg': '#15150e',
    '--ide-border': '#302a18',
    '--ide-text': '#e8e0c8',
    '--ide-muted': '#6a6040',
    '--ide-accent': '#d4a520',
    '--ide-header-bg': '#080804',
    '--disk-bg': '#12100a',
    '--disk-border-color': '#302a18',
    '--disk-bg-hover': '#1e1a10',
    '--disk-border-hover': '#d4a520',
    '--disk-bg-active': '#000000',
    '--disk-border-active': '#d4a520',
    '--port-bg': '#302a18',
    '--port-bg-hover': '#d4a520',
    '--port-bg-active': '#d4a520',
  },
  'Jade Circuit': {
    '--bg': '#040a08',
    '--text-main': '#c0e0d0',
    '--text-muted': '#3a6850',
    '--color-sys': '#2dd4a8',
    '--color-char': '#70b090',
    '--color-user': '#1a9a70',
    '--ide-bg': '#061210',
    '--ide-editor-bg': '#081a16',
    '--ide-border': '#183028',
    '--ide-text': '#c0e0d0',
    '--ide-muted': '#3a6850',
    '--ide-accent': '#2dd4a8',
    '--ide-header-bg': '#040a08',
    '--disk-bg': '#0a1810',
    '--disk-border-color': '#183028',
    '--disk-bg-hover': '#143020',
    '--disk-border-hover': '#2dd4a8',
    '--disk-bg-active': '#000000',
    '--disk-border-active': '#2dd4a8',
    '--port-bg': '#183028',
    '--port-bg-hover': '#2dd4a8',
    '--port-bg-active': '#2dd4a8',
  },
};

const tokenNameMap: Record<string, string> = {
  '--bg': '--wb-bg',
  '--text-main': '--wb-text',
  '--text-muted': '--wb-text-muted',
  '--color-sys': '--wb-color-a',
  '--color-char': '--wb-color-b',
  '--color-user': '--wb-color-c',
  '--disk-bg': '--wb-disk-bg',
  '--disk-border-color': '--wb-disk-border',
  '--disk-bg-hover': '--wb-disk-bg-hover',
  '--disk-border-hover': '--wb-disk-border-hover',
  '--disk-bg-active': '--wb-disk-bg-active',
  '--disk-border-active': '--wb-disk-border-active',
  '--disk-text-hover-override': '--wb-disk-text-hover',
  '--disk-text-active-override': '--wb-disk-text-active',
  '--port-bg': '--wb-port-bg',
  '--port-bg-hover': '--wb-port-bg-hover',
  '--port-bg-active': '--wb-port-bg-active',
};

export const RESETTABLE_THEME_TOKENS = [
  ...Object.values(tokenNameMap),
  '--wb-sys',
  '--wb-char',
  '--wb-user',
  '--wb-surface',
  '--wb-surface-hover',
  '--ide-bg',
  '--ide-editor-bg',
  '--ide-border',
  '--ide-text',
  '--ide-muted',
  '--ide-accent',
  '--ide-header-bg',
];

function mapTokens(tokens: ThemeTokenMap): ThemeTokenMap {
  const mapped: ThemeTokenMap = {};

  for (const [key, value] of Object.entries(tokens)) {
    mapped[tokenNameMap[key] ?? key] = value;
  }

  mapped['--wb-sys'] = mapped['--wb-color-a'];
  mapped['--wb-char'] = mapped['--wb-color-b'];
  mapped['--wb-user'] = mapped['--wb-color-c'];
  mapped['--wb-surface'] = 'color-mix(in srgb, var(--wb-text) 4%, transparent)';
  mapped['--wb-surface-hover'] = 'color-mix(in srgb, var(--wb-text) 6%, transparent)';
  return mapped;
}

export const WORLDBOOK_THEMES: WorldbookTheme[] = Object.entries(sourceThemes).map(([name, tokens]) => ({
  name,
  tokens: mapTokens(tokens),
}));

export const DEFAULT_THEME_NAME = WORLDBOOK_THEMES[0].name;

export function getTheme(name: string): WorldbookTheme {
  return WORLDBOOK_THEMES.find(theme => theme.name === name) ?? WORLDBOOK_THEMES[0];
}
